export const segmentsList = [
  { name: 'Alimentos e Bebidas' },
  { name: 'Arte e Antiguidades' },
  { name: 'Artigos Religiosos' },
  { name: 'Assinaturas e Revistas' },
  { name: 'Automóveis e Veículos' },
  { name: 'Bebês e Cia' },
  { name: 'Blu-Ray' },
  { name: 'Brindes / Materiais Promocionais' },
  { name: 'Brinquedos e Games' },
  { name: 'Casa e Decoração' },
  { name: 'CDs' },
  { name: 'Colecionáveis' },
  { name: 'Compras Coletivas' },
  { name: 'Construção e Ferramentas' },
  { name: 'Cosméticos e Perfumaria' },
  { name: 'Cursos e Educação' },
  { name: 'Discos de Vinil' },
  { name: 'DVDs' },
  { name: 'Eletrodomésticos' },
  { name: 'Eletrônicos' },
  { name: 'Emissoras de Rádio' },
  { name: 'Emissoras de Televisão' },
  { name: 'Empregos' },
  { name: 'Empresas de Telemarketing' },
  { name: 'Esporte e Lazer' },
  { name: 'Fitas K7 Gravadas' },
  { name: 'Flores, Cestas e Presentes' },
  { name: 'Fotografia' },
  { name: 'HD-DVD' },
  { name: 'Igrejas / Templos / Instituições Religiosas' },
  { name: 'Indústria, Comércio e Negócios' },
  { name: 'Infláveis Promocionais' },
  { name: 'Informática' },
  { name: 'Ingressos' },
  { name: 'Instrumentos Musicais' },
  { name: 'Joalheria' },
  { name: 'Lazer' },
  { name: 'LD' },
  { name: 'Livros' },
  { name: 'MD' },
  { name: 'Moda e Acessórios' },
  { name: 'Motéis' },
  { name: 'Música Digital' },
  { name: 'Natal' },
  { name: 'Negócios e Oportunidades' },
  { name: 'Outros Serviços' },
  { name: 'Outros Serviços de Avaliação' },
  { name: 'Papelaria e Escritório' },
  { name: 'Páscoa' },
  { name: 'Pet Shop' },
  { name: 'Saúde' },
  { name: 'Serviço Advocaticios' },
  { name: 'Serviço de Distribuição de Jornais / Revistas' },
  { name: 'Serviços Administrativos' },
  { name: 'Serviços Artísticos' },
  { name: 'Serviços de Abatedouros / Matadouros' },
  { name: 'Serviços de Aeroportos' },
  { name: 'Serviços de Agências' },
  { name: 'Serviços de Aluguel / Locação' },
  { name: 'Serviços de Armazenagem' },
  { name: 'Serviços de Assessorias' },
  { name: 'Serviços de Assistência Técnica / Instalações' },
  { name: 'Serviços de Associações' },
  { name: 'Serviços de Bancos de Sangue' },
  { name: 'Serviços de Bibliotecas' },
  { name: 'Serviços de Cartórios' },
  { name: 'Serviços de Casas Lotéricas' },
  { name: 'Serviços de Confecções' },
  { name: 'Serviços de Consórcios' },
  { name: 'Serviços de Consultorias' },
  { name: 'Serviços de Cooperativas' },
  { name: 'Serviços de Despachante' },
  { name: 'Serviços de Engenharia' },
  { name: 'Serviços de Estacionamentos' },
  { name: 'Serviços de Estaleiros' },
  { name: 'Serviços de Exportação / Importação' },
  { name: 'Serviços de Geólogos' },
  { name: 'Serviços de joalheiros' },
  { name: 'Serviços de Leiloeiros' },
  { name: 'Serviços de limpeza' },
  { name: 'Serviços de Loja de Conveniência' },
  { name: 'Serviços de Mão de Obra' },
  { name: 'Serviços de Órgão Públicos' },
  { name: 'Serviços de Pesquisas' },
  { name: 'Serviços de Portos' },
  { name: 'Serviços de Saúde / Bem Estar' },
  { name: 'Serviços de Seguradoras' },
  { name: 'Serviços de Segurança' },
  { name: 'Serviços de Sinalização' },
  { name: 'Serviços de Sindicatos / Federações' },
  { name: 'Serviços de Traduções' },
  { name: 'Serviços de Transporte' },
  { name: 'Serviços de Utilidade Pública' },
  { name: 'Serviços em Agricultura / Pecuária / Piscicultura' },
  { name: 'Serviços em Alimentação' },
  { name: 'Serviços em Arte' },
  { name: 'Serviços em Cine / Foto / Som' },
  { name: 'Serviços em Comunicação' },
  { name: 'Serviços em Construção' },
  { name: 'Serviços em Ecologia / Meio Ambiente' },
  { name: 'Serviços em Eletroeletrônica / Metal Mecânica' },
  { name: 'Serviços em Festas / Eventos' },
  { name: 'Serviços em Informática' },
  { name: 'Serviços em Internet' },
  { name: 'Serviços em Jóias / Relógios / Óticas' },
  { name: 'Serviços em Telefonia' },
  { name: 'Serviços em Veículos' },
  { name: 'Serviços Esotéricos / Místicos' },
  { name: 'Serviços Financeiros' },
  { name: 'Serviços Funerários' },
  { name: 'Serviços Gerais' },
  { name: 'Serviços Gráficos / Editoriais' },
  { name: 'Serviços para Animais' },
  { name: 'Serviços para Deficientes' },
  { name: 'Serviços para Escritórios' },
  { name: 'Serviços para Roupas' },
  { name: 'Serviços Socias / Assistenciais' },
  { name: 'Sex Shop' },
  { name: 'Shopping Centers' },
  { name: 'Tabacaria' },
  { name: 'Tarifas Bancárias' },
  { name: 'Tarifas Telefônicas' },
  { name: 'Telefonia' },
  { name: 'Turismo' },
];
